appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: dThyQU3CAB1dOUZNoNdlW7zZ5jtAcRuZ6RZwXxG4JFsXAj9t3Q4Y1iHZOUxQZXOEFd4sNJx8Ek6SMmaRbZCAAlvjxme12MMmIGV1qsdl/+MizCEBjM43GSWLeSFRAe3LV01gb7SS/unFKN6f9Z3d4yQpRdsNwdj5aYtX12vwaUlh5Gn67pohFol82+OgHvU95ecnC7fcXDkpVAvSkAT7sL8uVaNXmVSW6KdviFajQfWYI33Gojvrfi6MdDu41fMiJQeeycYjep6xozSSTU1UXfaDjCGvkS0iyLHobOeKOFJ28sVKeqiA5QJEAztOQP947GlsN9LRMMR73GUFBHL5Ca+PK8KVWBi4SKZ+9pUVMkl9JlLJzRQum7ohqU5UsVMORc15IO2JKiBn1CUghN0el06RiSIDbZpFvPP3OV0SJEOrqC33ooWiQ6jcFDrbfz8siwLpkcrUee9S5R/fLsd89/X+dVSXbG1gTi0oYJWzr64uXNnEhB4kas1ybVJDT67Ux6TkmxD5NJ+Dh2CLtjDDNaNjupXCEmVTh4WKAY/ZYOC/ZF2fZ0gUrNoNm1t3nwfNOOilhM6QHgilcgksvBp9iLmtNk9GYpfD5Y0ozIEY1ScsbjFlgvJQU6YvK5SyT93pRcZQ2+mnVhOjw6zBjLUZKfd+Oq2rk57NYwR0hhMHqlo=
